### PR TITLE
Fix unzLocateFile 3rd parameter

### LINKED ISSUE #745: Compatibility issues in unzLocateFile
Hi,

I've run into a building issue with the `libdigidocpp` package when switching from minizip (madler/zlib part) to minizip-ng (built with MZ_COMPAT flag).

I reported this to their upstream [1], but now when I think about it, it may be the issue of minizip-ng as it should be fully compatible, but it's not.

Could you please take a look at the error and help me resolve this building issue? I was trying to find some sort of PORTING document in your Github, but there is nothing that would look like it.
Thank you

[1] https://github.com/open-eid/libdigidocpp/issues/569

### PR DESCRIPTION
**Pull request by tuliom**
Replace the previous type with one that is compatible with an int in order to be identical to the interface used in madler's zlib.

Fixes #745.

### CODE REVIEW

**Comment by ljavorsk** [comment]
@nmoinvaz Could you please review this PR?

Thank you

File: mz_compat.c [hunk 1]
```diff
@@ -1093,7 +1093,13 @@ int unzGoToNextFile(unzFile file) {
     return err;
 }
 
-int unzLocateFile(unzFile file, const char *filename, unzFileNameComparer filename_compare_func) {
+#ifdef WIN32
+#define DEFAULT_IGNORE_CASE 1
```
Comment (nmoinvaz) [inline mz_compat.c:1097]: Two space indent.

File: mz_compat.c [hunk 2]
```diff
@@ -1093,7 +1093,13 @@ int unzGoToNextFile(unzFile file) {
...
+#else
+#define DEFAULT_IGNORE_CASE 0
```
Comment (nmoinvaz) [inline mz_compat.c:1099]: Two space indent.

File: mz_compat.c (hunk 1 above)
Comment (nmoinvaz) [reply mz_compat.c:1097]: Also let's prefix these with `UNZ_`.

File: mz_compat.c [hunk 3]
```diff
@@ -1111,12 +1117,19 @@ int unzLocateFile(unzFile file, const char *filename, unzFileNameComparer filena
...
-            result = mz_path_compare_wc(filename, file_info->filename, !case_sensitive);
+        uint8_t ignore_case;
+        switch (filename_case) {
+          case 0:
+            ignore_case = DEFAULT_IGNORE_CASE;
+            break;
+          case 1:
+            ignore_case = 0;
+            break;
+          case 2: // Fall through.
```
[the remark this answers is not in the document]
Comment (tuliom) [reply mz_compat.c]: Done.

File: mz_compat.c [hunk 4]
```diff
@@ -1111,12 +1117,19 @@ int unzLocateFile(unzFile file, const char *filename, unzFileNameComparer filena
         if (err != MZ_OK)
             break;
 
-        if ((intptr_t)filename_compare_func > 2) {
-            result = filename_compare_func(file, filename, file_info->filename);
-        } else {
-            int32_t case_sensitive = (int32_t)(intptr_t)filename_compare_func;
-            result = mz_path_compare_wc(filename, file_info->filename, !case_sensitive);
+        uint8_t ignore_case;
```
[the remark this answers is not in the document]
Comment (tuliom) [reply mz_compat.c]: @nmoinvaz I didn't understand this part.
I moved this line to the declaration block at the beginning of the function.
Please let me know if I got this wrong.
Thanks!

File: mz_compat.c [hunk 5]
```diff
@@ -1093,12 +1093,19 @@ int unzGoToNextFile(unzFile file) {
     return err;
 }
 
-int unzLocateFile(unzFile file, const char *filename, unzFileNameComparer filename_compare_func) {
+#ifdef WIN32
+  #define UNZ_DEFAULT_IGNORE_CASE 1
```
Comment (nmoinvaz) [inline mz_compat.c:1097]: Sorry, I should have clarified, in this project I use `#  define` when indented.

File: mz_compat.c [hunk 6]
```diff
@@ -1093,12 +1093,19 @@ int unzGoToNextFile(unzFile file) {
...
+  #define UNZ_DEFAULT_IGNORE_CASE 0
+#endif
+
+int unzLocateFile(unzFile file, const char *filename, unzFileNameCase filename_case) {
     mz_compat *compat = (mz_compat *)file;
     mz_zip_file *file_info = NULL;
     uint64_t preserve_index = 0;
     int32_t err = MZ_OK;
     int32_t result = 0;
+    uint8_t ignore_case;
```
Comment (nmoinvaz) [inline mz_compat.c:1108]: default to `UNZ_DEFAULT_IGNORE_CASE`?

File: mz_compat.c [hunk 7]
```diff
@@ -1111,12 +1118,17 @@ int unzLocateFile(unzFile file, const char *filename, unzFileNameComparer filena
         if (err != MZ_OK)
             break;
 
-        if ((intptr_t)filename_compare_func > 2) {
-            result = filename_compare_func(file, filename, file_info->filename);
-        } else {
-            int32_t case_sensitive = (int32_t)(intptr_t)filename_compare_func;
-            result = mz_path_compare_wc(filename, file_info->filename, !case_sensitive);
+        switch (filename_case) {
```
Comment (nmoinvaz) [inline mz_compat.c:1121]: Since `ignore_case` is now defaulted. this becomes:
```c
if (filename_case == 1) {
   ignore_case = 0;
} else if (filename_case > 1) {
   ignore_case = 1;
}
```

Comment (nmoinvaz) [reply mz_compat.c:1121]: And actually this logic can go outside of the `while` loop.

File: mz_compat.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (nmoinvaz) [reply mz_compat.c]: Yes, that is correct.

File: mz_compat.c (hunk 5 above)
Comment (tuliom) [reply mz_compat.c]: Oops. Fixed.

File: mz_compat.c (hunk 6 above)
Comment (tuliom) [reply mz_compat.c]: Done.

File: mz_compat.c (hunk 7 above)
Comment (tuliom) [reply mz_compat.c]: Done.
Thanks again!

**Review by nmoinvaz — APPROVED** [review]
